exports.seed = knex => (
    knex('ingredients').del()
        .then(() =>
            knex('ingredients').insert([
                { id: 1, name: 'Дрожжевое кислое тесто', type_id: 1 },
                { id: 2, name: 'Пресное (бездрожжевое) тесто', type_id: 1 },
                { id: 3, name: 'Слоёное тесто', type_id: 1 },
                { id: 4, name: 'Сыр Моцарелла', type_id: 2 },
                { id: 5, name: 'Сыр Пармезан', type_id: 2 },
                { id: 6, name: 'Сыр Дор Блю', type_id: 2 },
                { id: 7, name: 'Сыр Фонтина', type_id: 2 },
                { id: 8, name: 'Сыр Чеддер', type_id: 2 },
                { id: 9, name: 'Курица', type_id: 3 },
                { id: 10, name: 'Говядина', type_id: 3 },
                { id: 11, name: 'Свинина', type_id: 3 },
                { id: 12, name: 'Бекон', type_id: 3 },
                { id: 13, name: 'Ветчина', type_id: 3 },
                { id: 14, name: 'Пепперони', type_id: 3 },
                { id: 15, name: 'Пицца-соус', type_id: 5 },
                { id: 16, name: 'Сливочный соус', type_id: 5 },
                { id: 17, name: 'Томатный соус', type_id: 5 },
                { id: 18, name: 'Шампиньёны', type_id: 4 },
                { id: 19, name: 'Белые грибы', type_id: 4 },
                { id: 20, name: 'Грибной жюльен', type_id: 4 },
                { id: 21, name: 'Зелень', type_id: 7 },
                { id: 22, name: 'Укроп', type_id: 7 },
                { id: 23, name: 'Помидоры', type_id: 6 },
                { id: 24, name: 'Картофель', type_id: 6 },
                { id: 25, name: 'Лук красный', type_id: 6 },
                { id: 26, name: 'Лук зелёный', type_id: 7 },
                { id: 27, name: 'Огурцы маринованные', type_id: 6 },
                { id: 28, name: 'Кунжут', type_id: 7 },
                { id: 29, name: 'Перец болгарский', type_id: 7 },
            ]))
)
